---

base:
  packages:
    install:    
      - unzip
      - build-essential
      - software-properties-common
      - jq
      - lvm2
      - whois
      - aptitude
    uninstall:
      - thunderbird