---

- name: add postgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present  

- name: add postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main
    state: present
    filename: postgresql  

- name: install postgresql and tools
  apt:
    name: postgresql-10,pgadmin3
    state: latest

# Bit of a problem child as it prompts for setup
#- name: install mysql and tools
#  apt:
#    name: mariadb-server,mariadb-client,mysql-workbench
#    state: latest
    