---

# Snaps only available 18.04 and above
- name: install snap applications
  command: "snap install --classic {{item}}"
  args:
    creates: "/snap/bin/{{item}}"
  loop: "{{applications.snaps.install}}"  
  when: ansible_lsb.major_release|int >= 18
  ignore_errors: yes