---

- include: repositories.yml

- name: install additional packages
  apt:
    name: "{{item}}"
    state: latest  
  loop: "{{tools.packages.install}}"

- name: install vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb

# Will have to do this manually until ansible has a snap plugin
- name: install postman from snap 
  command: snap install postman
  args:
    creates: /snap/bin/postman