---

- name: add nodejs repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x {{ubuntu.distro}} main
    state: present
    filename: nodesource.list

- name: add vscode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode.list    

- name: add vscode repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present        

- name: add virtualbox repository
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ubuntu.distro}} contrib
    state: present
    filename: virtualbox.list      

- name: add virtualbox repository key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present         

- name: install additional packages
  apt:
    name: "{{item}}"
    state: latest  
  with_items: "{{tools.packages.install}}"

- name: install vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb