- name: docker install prerequisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-pip

- name: create docker group
  group:
    name: docker
    state: present

- name: install docker support for ansible
  pip:
    name: docker-py    

- name: add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present    
    
- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: true
    filename: docker    

- name: install docker
  apt:
    name: "{{docker.name}}"
    state: latest

- name: copy docker daemon file
  copy:
    src: "{{role_path}}/files/daemon.json"
    dest: /etc/docker/daemon.json
    
- name: start docker deamon
  service:
    name: docker
    state: started
    enabled: yes

- name: get latest docker compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/{{docker.compose}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  creates: /usr/local/bin/docker-compose