- name: docker install prerequisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - overlay2
    - device-mapper-persistent-data
    - lvm2
    - python-pip

- name: create docker group
  group:
    name: docker
    state: present

- name: install docker support for ansible
  pip:
    name: docker-py    

- name: add docker repository
  apt_repository:
    name: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu.distro}} stable
    state: present
    filename: docker.list    

- name: add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present      

- name: install docker
  apt:
    name: "{{docker.name}}={{docker.version}}"
    state: present
    update_cache: yes       
    
- name: start docker deamon
  service:
    name: docker
    state: started
    enabled: yes