---

- name: update installed packages
  apt:
    upgrade: yes
    
- include: virtualbox.yml

- name: install base packages
  apt:
    name: "{{item}}"
    state: latest  
    update_cache: true
  with_items: "{{base.packages.install}}"

- name: uninstall distro packages
  apt:
    name: "{{item}}"
    state: absent  
  with_items: "{{base.packages.uninstall}}"
  ignore_errors: yes

- name: clean up unused packages
  apt:
    autoremove: yes
    autoclean: yes
  ignore_errors: yes  